name: Release

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/workflows/release.yml
      - .goreleaser.yaml
  push:
    tags: ['v*.*.*']

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7
        if: github.event_name == 'pull_request'
        with:
          version: '~> v2'
          args: release --snapshot
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # Disable the monorepo feature
          GORELEASER_CURRENT_TAG: v0.0.1
          GORELEASER_PREVIOUS_TAG: v0.0.1-alpha

      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7
        if: github.event_name != 'pull_request'
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
